### ISSUE TITLE
Error: EISDIR, illegal operation on a directory

### ISSUE THREAD

**Issue by danielanteloagra** [ecomfe/htmlcs#23]
Hi,

I´ve installed htmlcs via npm and now trying to run from the command line but get the following error:

What am I missing? Any help would be appreciated. 

Also was wondering how this works with templating files such as twig or smarty.

```
daniel$ htmlcs Resources/views/

fs.js:488
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:488:19)
    at Object.fs.readFileSync (fs.js:322:28)
    at Object.hintFile (/usr/local/lib/node_modules/htmlcs/index.js:73:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/htmlcs/bin/htmlcs:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by nighca** [comment]
Hi,

While you run `htmlcs` in the command line, the first arg should be path of a file instead of a folder (that's not supported yet). You can try [`fecs`](https://github.com/ecomfe/fecs), whose html-hint feature is based on `htmlcs`, for more friendly usage.

Dealing with template files will be troublesome, for there are many templates with different syntax. Now we take it as simple HTML code. We will consider some better solutions further.
