### ISSUE TITLE
"walk" not in dependencies

### ISSUE THREAD

**Issue by radek-holy** [ecomfe/htmlcs#67]
A freshly installed `htmlcs@0.1.8` fails with:
```
module.js:339
    throw err;
    ^

Error: Cannot find module 'walk'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/test/node_modules/htmlcs/lib/cli/helper.js:8:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```
I guess that the reason is that `walk` is in `devDependencies` instead of just `dependencies`.

**Comment by nighca** [comment]
Thanks for your feedback!

**Comment by nighca** [comment]
https://github.com/ecomfe/htmlcs/pull/73
