### ISSUE TITLE
Running on a directory results in "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by radek-holy** [ecomfe/htmlcs#68]
When I run `htmlcs hint ./`, I get:
```
/tmp/test/node_modules/walk/lib/node-type-emitter.js:20
    fnodeTypesPlural.concat("nodes", "errors").forEach(function (fnodeTypePlural) {
                     ^

RangeError: Maximum call stack size exceeded
    at Object.createNodeGroups (/tmp/test/node_modules/walk/lib/node-type-emitter.js:20:22)
    at Walker._wReaddirHandler (/tmp/test/node_modules/walk/lib/walk.js:158:35)
    at Walker._wWalkSync (/tmp/test/node_modules/walk/lib/walk.js:238:8)
    at Walker._wNext (/tmp/test/node_modules/walk/lib/walk.js:263:12)
    at Walker._wNext (/tmp/test/node_modules/walk/lib/walk.js:272:17)
    at Walker._wNext (/tmp/test/node_modules/walk/lib/walk.js:272:17)
    at Walker._wNext (/tmp/test/node_modules/walk/lib/walk.js:272:17)
    at Walker._wOnEmitDone (/tmp/test/node_modules/walk/lib/walk.js:124:8)
    at nextWhenReady (/tmp/test/node_modules/walk/lib/node-type-emitter.js:69:29)
    at Object.emitPluralEvents [as emitNodeTypeGroups] (/tmp/test/node_modules/walk/lib/node-type-emitter.js:77:5)
```

I guess that to reproduce it, a populated `node_modules` directory in the target directory must be present and that it is related to https://github.com/coolaj86/node-walk/issues/33.

**Comment by nighca** [comment]
Thanks for your feedback, I'll fix it with path globs support.
